print("kerro 3 kokonaislukua:")
Luku_1 = input()
Luku_2 = input()
Luku_3 = input()
Summa = float(Luku_1) + float(Luku_2) + float(Luku_3)
Tulo = float(Luku_1) * float(Luku_2) * float(Luku_3)
Keskiarvo = float(Summa) / 3
print("Lukujen Summa on:" + str(Summa))
print("Lukujen Tulo on:" + str(Tulo))
print("Lukujen Keskiar on:" + str(Keskiarvo))